### ISSUE TITLE
Error after updating core to 2025.2.4

### ISSUE THREAD

**Issue by thcasssio** [icarome/zk_teco#3]
After updating the core to 2025.2.4, I get the following error when checking the configuration:

 Configuration warnings
Platform error 'lock' from integration 'zk_teco' - cannot import name 'SUPPORT_OPEN' from 'homeassistant.components.lock' (/usr/src/homeassistant/homeassistant/components/lock/__init__.py)
Platform error 'lock' from integration 'zk_teco' - cannot import name 'SUPPORT_OPEN' from 'homeassistant.components.lock' (/usr/src/homeassistant/homeassistant/components/lock/__init__.py)

**Comment by icarome** [comment]
It should be fixed now. Please let me now!
